style"gtkbutton"{
xthickness=0
ythickness=0
GtkButton::inner-border={4,4,2,2}
GtkButton::image-spacing=5
GtkWidget::wide-separators=1
GtkWidget::separator-height=0
GtkWidget::separator-width=0
GtkButton::interior_focus = 1
GtkWidget::focus_padding = 0
GtkButton::child-displacement-x=0
GtkButton::child-displacement-y=0
GtkButton::displace-focus=1
GtkButton::default-outside-border={0,0,0,}
GtkButton::default-border={0,0,0,}
fg[NORMAL]=@windowtext
fg[PRELIGHT]=@windowtext
fg[SELECTED]=@windowtext
fg[ACTIVE]=@windowtext
fg[INSENSITIVE]=@inactivewindowtext
bg[NORMAL]=@button
bg[PRELIGHT]=shade (1.025, @button)
bg[SELECTED]=@hilight
bg[ACTIVE]=shade (0.90, @button)
bg[INSENSITIVE]=@button
text[NORMAL]=@buttontext
text[PRELIGHT]=@buttontext
text[SELECTED]=@buttontext
text[ACTIVE]=@buttontext
text[INSENSITIVE]=@inactivewindowtext
engine"pixmap"{
image{
function=SHADOW
shadow=OUT
file="../images/button-normal.svg"
border={2,2,2,2}
stretch=TRUE}
image{
function=SHADOW
shadow=IN
file="../images/button-active.svg"
border={1,1,1,1}
stretch	=TRUE}
image{
function=BOX
state=NORMAL
detail="buttondefault"
border={1,1,1,1}
file="../images/button-default.svg"
stretch=TRUE}
image{
function=FOCUS
detail="button"
border={1,1,1,1}
file="../images/button-default.svg"
stretch=TRUE}
image{
function=BOX
detail="hseparator"
file="../images/transparent.png"
stretch=TRUE}
image{
function=BOX
detail="vseparator"
file="../images/transparent.png"
stretch=TRUE}
image{
function=HLINE
detail="hseparator"
file="../images/transparent.png"
stretch=TRUE}
image{
function=VLINE
detail="vseparator"
file="../images/transparent.png"
stretch=TRUE}}}
widget"*GtkButton*"style"gtkbutton"
widget"*GtkToolButton*"style"gtkbutton"
widget"*GtkToggleButton*"style"gtkbutton"
class"*GtkButton*"style"gtkbutton"

style"gtkoptionmenu"{
xthickness=0
ythickness=3}
widget_class"*GtkOptionMenu"style"gtkoptionmenu"

style"gtklnkbutton"{
xthickness=0
ythickness=0
bg[NORMAL]=@window
bg[PRELIGHT]=@window
bg[SELECTED]=@window
bg[ACTIVE]=@window
bg[INSENSITIVE]=@window
engine"pixmap"{
image{
function=SHADOW
shadow=IN
file="../images/transparent.png"
stretch=TRUE}
image{
function=SHADOW
shadow=ETCHED_IN
file="../images/transparent.png"
stretch=TRUE}
image{
function=SHADOW
shadow=OUT
file="../images/transparent.png"
stretch=TRUE}
image{
function=SHADOW
shadow=ETCHED_OUT
file="../images/transparent.png"
stretch=TRUE}
image{
function=SHADOW
shadow=NONE
file="../images/transparent.png"
stretch=TRUE
}}}widget"*GtkLinkButton*"style"gtklnkbutton"
widget"*GtkButton*GtkLabel"style"gtkimagelabel"
widget"*GtkButton*GtkImage"style"gtkimagelabel"
