style"gtktoolbar"{
xthickness=0
ythickness=0
GtkToolbar::shadow-type=GTK_SHADOW_NONE
GtkToolbar::space-style=GTK_TOOLBAR_SPACE_LINE
GtkToolbar::space-size=2
GtkToolbar::internal-padding=1
bg[NORMAL]=@window
bg[PRELIGHT]=@window
bg[SELECTED]=@window
bg[ACTIVE]=@window
bg[INSENSITIVE]=@window
fg[NORMAL]=@windowtext
fg[PRELIGHT]=@windowtext
fg[SELECTED]=@windowtext
fg[ACTIVE]=@windowtext
fg[INSENSITIVE]=@inactivewindowtext
engine"pixmap"{
image{
function=SHADOW
shadow=NONE
file="../images/transparent.png"
stretch=TRUE}}}
class"GtkToolbar"style"gtktoolbar"
widget"*GtkToolbar*Label*"style"gtkimagelabel"
widget"*GtkToolbar*Image*"style"gtkimagelabel"

