style"gtkmenubar"{
xthickness=0
ythickness=0
GtkMenuItem::horizontal-padding=4
GtkMenuBar::shadow-type=GTK_SHADOW_NONE
GtkMenuBar::internal-padding=2
bg[NORMAL]=@window
bg[PRELIGHT]=@hilight
bg[SELECTED]=@hilight
bg[ACTIVE]=@hilight
bg[INSENSITIVE]=@window
fg[NORMAL]=@windowtext
fg[PRELIGHT]=@hilighttext
fg[SELECTED]=@windowtext
fg[ACTIVE]=@windowtext
fg[INSENSITIVE]=@inactivewindowtext
engine"pixmap"{
image{
function=SHADOW
shadow=NONE
file="../images/transparent.png"
stretch=TRUE}
image{
function=BOX
shadow=OUT
state=PRELIGHT
file="../images/menubaritemhilight.svg"
border={1,1,3,1}
stretch=TRUE
overlay_file="../images/menubaritemshadow.svg"
overlay_border={1,1,3,1}
overlay_stretch=TRUE}}}
widget_class"*.<GtkMenuBar>*"style"gtkmenubar"
widget_class"*.<GtkMenuBar>*<GtkLabel>*"style"gtkimagelabel"
