style"gtkprogressbar"{
xthickness=0
ythickness=0
GtkProgressBar::xspacing=0
GtkProgressBar::yspacing=0
fg[NORMAL]=@windowtext
fg[PRELIGHT]=@hilighttext
fg[SELECTED]=@windowtext
fg[ACTIVE]=@windowtext
fg[INSENSITIVE]=@inactivewindowtext
bg[NORMAL]=@window
bg[PRELIGHT]=@hilight
bg[SELECTED]=@hilight
bg[ACTIVE]=@hilight
bg[INSENSITIVE]=@window
base[NORMAL]=@window
base[PRELIGHT]=@window
base[ACTIVE]=@hilight
base[SELECTED]=@hilight
base[INSENSITIVE]=@window
text[NORMAL]=@basetext
text[PRELIGHT]=@hilighttext
text[ACTIVE]=@hilighttext
text[SELECTED]=@hilighttext
text[INSENSITIVE]=@inactivewindowtext
engine"pixmap"{
image{
function=BOX
detail="trough"
file="../images/progressbar-trough.svg"
border={1,1,1,1}
stretch=TRUE}
image{
function=BOX
detail="bar"
file="../images/button-default.svg"
stretch=TRUE
overlay_file="../images/progressbar-bar.svg"
overlay_border={2,2,2,2}
overlay_stretch=TRUE}}}
class"GtkProgressBar"style"gtkprogressbar"
