style"gtkstatusbar"
{
GtkStatusbar::shadow-type=GTK_SHADOW_NONE
engine"pixmap"
{
image
{
function=RESIZE_GRIP
detail="statusbar"
overlay_file="../images/resizegrip.png"
overlay_stretch=TRUE
overlay_border={0,11,0,11}
}
}
}
widget_class"*Gtk*Statusbar*"style"gtkstatusbar"
